### ISSUE TITLE
Minor Issues with stack sizes and bottles

### ISSUE THREAD

**Issue by BioMasterZap** [skniro/UsefulFood-Reborn#2]
Nothing too major or gamebreaking, but when reviewing the foods for v1.1.1 on Fabric 1.20.4, I noticed some inconsistent behaviors that I thought were worth noting.

In Vanilla, Cakes and Stews only stack to 1. All the Cakes in this mod (Apple Cake, Caramel Cake, Chocolate Cake, and Magic Cake) stack to 64. Likewise, Fruit Salad, Magic Fruit Salad, Trail Mix, Magic Ice Cream, and Fish Soup stack to 64, but all the other bowl foods in the mod only stack to 1.

Another thing I noticed is that Juices and Lily Tea do not return the Glass Bottle when consumed. The Milks/Cocoas do return the bottle, but only if it the last of the stack. Fruit Salad, Magic Fruit Salad, and Magic Ice Cream, never return bowls while Trail Mix and Fish Soup always return a bowl, but if you eat it with more than one is stacked, it replaces the entire stack with 1 bowl.

Also, I am not seeing a working recipe for Lily Tea. When I use JEI/REI, it is just showing a Glass Bottle, which doesn't work. It might be something on my end, but might be worth double-checking the recipe.

**Comment by skniro** [comment]
Thanks your report!

**Comment by skniro** [comment]
Fix in Mod Version1.2.0+
