### ISSUE TITLE
Fish 'n' Chips aren't craftable.

### ISSUE THREAD

**Issue by StupidRepo** [skniro/UsefulFood-Reborn#3]
REI says I can craft Fish 'n' Chips with simply 1x French Fries.

![image](https://github.com/skniro/UsefulFood-Reborn/assets/69256931/e2f2e3b8-18bc-4b20-b2c1-41208ff06ac5)

However, when I try this, nothing happens.
![image](https://github.com/skniro/UsefulFood-Reborn/assets/69256931/15c82ef8-f396-4d1f-a7b3-51e7297d8bb8)

Am I missing something?

(Also, there's a localisation issue. It's spelt `Fish n' Chips` when it should be `Fish 'n' Chips`. Note the extra `'`)

**Comment by skniro** [comment]
Mod Version?

**Comment by skniro** [comment]
And i should remove ’ or add '(like 'n'). English isn't my first language, So i need some help.

**Comment by StupidRepo** [comment]
Hey, the mod version is `1.2.0-1.21-Fabric`. I see you have pushed the update fixing this recipe.
The correct spelling would be `Fish 'n' Chips` with just a normal apostrophe (`'`) 😁

**Comment by skniro** [comment]
Fix in 1.2.2-1.21Fabric/Forge. Thanks your report!

**Comment by StupidRepo** [comment]
No problem :D
