### ISSUE TITLE
Added cakes revert to default cake with placed candle

### ISSUE THREAD

**Issue by DrRockwell** [skniro/UsefulFood-Reborn#5]
Nothing too major, but I noticed that when you place a candle on the added cakes (to make a birthday cake for example) it changes that cake to the default cake. This does end up replacing the cake as a block as well. I have tried with all 4 cakes and they all do the same. 

example:
Strawberry cake + candle --> normal cake + candle

But this is a really cool mod, and thanks for making it work for us players!

**Comment by skniro** [comment]
I try to fix it in 1.20.4, but the fix make a new bug it will convert vanilla cake to caramel cake. I don't know why case this new issue.

**Comment by skniro** [comment]
Try 1.2.5
